### PR TITLE
feat: Adds semantic release and Travis

### PR DESCRIPTION
**Pull request by Teapane**
- Use Semantic Release
- Adds a `travis.yml` file

@c0, lets chat when you get online.

### CODE REVIEW

**Comment by Teapane** [comment]
We will need to setup `semantic-release` with a github user and npm user: 
```
npm install -g semantic-release-cli
semantic-release-cli setup
```

**Comment by Teapane** [comment]
So it looks like [Build #91.](https://travis-ci.org/rentpath/preload-json.js/jobs/111540222) is :green_heart: . Once this is merged, it should push to `npm`. :sunglasses:

**Comment by Teapane** [comment]
@c0 it looks like it is failing on some of those specified `node versions`.

**Comment by Teapane** [comment]
:boom:

**Comment by c0** [comment]
Thanks @Teapane!

**Pull request merged**
